kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: dotnet:2.1
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: vote-odo
  Name: dotnet-worker-wwtf
  Envs:
  - Name: REDIS_PASSWORD
    Value: "1234"
  - Name: REDIS_HOST
    Value: redis
  - Name: POSTGRESQL_HOST
    Value: postgresql
  - Name: POSTGRESQL_USERNAME
    Value: vote
  - Name: POSTGRESQL_PASSWORD
    Value: "1234"
  - Name: POSTGRESQL_DATABASE
    Value: vote
