kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: python:2.7
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: vote-odo
  Name: python-vote-zoqw
  Envs:
  - Name: REDIS_HOST
    Value: redis
  - Name: REDIS_PASSWORD
    Value: "1234"
  Url:
  - Name: python-vote-zoqw-8080
    Port: 8080
