apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: vote-tilt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: centos/postgresql-95-centos7
        name: postgres
        env:
        - name: POSTGRESQL_USER
          value: "vote"
        - name: POSTGRESQL_PASSWORD
          value: "1234"
        - name: POSTGRESQL_DATABASE
          value: "vote"
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: "changeme"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      volumes:
      - name: postgresql-data
        emptyDir: {} 
