apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  labels:
    app: result
    app.kubernetes.io/managed-by: tilt
  name: result
  namespace: vote-tilt
spec:
  host: ''
  to:
    kind: Service
    name: result
    weight: 100
status:
  ingress:
  - routerName: default
    wildcardPolicy: None